spring:
    application:
        name: springboot-soft-delete-example
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: pwd123
        url: jdbc:mysql://localhost:3306/soft_delete
        username: fajar
        hikari:
            minimum-idle: 5
            maximum-pool-size: 20
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format-sql: true
        show-sql: true

logging:
    level:
        web: DEBUG
        org.springframework.security: DEBUG